### ISSUE TITLE
Should backup on remote server ?

### ISSUE THREAD

**Issue by xcarpentier** [SimpliField/ansible-mongo-backup#1]

**Comment by SebastienElet** [comment]
You could connect from a remote server, or backup on a replicaset secondary.

**Comment by xcarpentier** [comment]
Ok, but I think it's a good practice to copy the backup to S3 or other storage server, outside of the current server. No ?

**Comment by SebastienElet** [comment]
Of course, you could rsync them, or use bacula or any other backup system/provider.

This role only trigger a mongodump in a cron, you could use it with another role for move/copy the dumps on another system/providier.
